config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :users, only: [:create] do
    collection do 
      get :sign_up 
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, length: { minimum: 2 }
  validates :email, uniqueness: true, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
  message: "Your email format is wrong" }
  validates :password, length: { minimum: 6 }

  before_create :encrypt_password

  def self.login(options)
    if options[:email] && options[:password]
      find_by(email: options[:email],
              password: Digest::SHA1.hexdigest(options[:password]))
    end
  end

  private

  def encrypt_password
    self.password = change(password)
  end

  def change(str)
    Digest::SHA1.hexdigest(str)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :user_signed_in?, :current_user

  private

  def not_authorized
    redirect_to root_path, notice: '權限不足'
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_token])
  end

  def user_signed_in?
    current_user != nil
  end

  def authenticate_user!
    redirect_to root_path, notice: "請登入會員" if not user_signed_in?
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  
  def sign_in
    @user = User.new
  end

  def login
    @user = User.login(clean_params)
    if @user
      sign_in_user(@user)
      redirect_to root_path, notice: 'succeed to login'
    else
      redirect_to sign_in_users_path, notice: 'Your email or password is incorrect'
    end
  end

  def sign_up
    @user = User.new
  end

  def create
    @user = User.new(clean_params)
    if @user.save
      redirect_to root_path, notice: 'succeed to sign up'
    else
      render :sign_up
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)

    if @user.update(clean_params)
      redirect_to root_path, notice: 'succeed to update'
    else
      render :sign_up
    end
  end

  def sign_out
    sign_out_user
    redirect_to root_path, notice: 'sign out!'
  end

  private

  def clean_params
    params.require(:user).permit(:email, :name, :password)
  end

  def sign_in_user(user)
    session[:user_token] = user.id
  end

  def sign_out_user
    session[:user_token] = nil
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <h1 class="text-center h3 text-danger"><%= notice %></h1>
    <h1 class="text-center h3 text-danger"><%= alert %></h1>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<ul class="nav border-bottom border-top border-dark h3">
  <li class="nav-item mx-4">
    <%= link_to 'sign up',sign_up_users_path, id:'sign_up_link' %>
  </li>
  <li class="nav-item mx-4">
    <%= link_to 'sign in', sign_in_users_path, id:'sign_in_link'%>
  </li>
  <li class="nav-item mx-4">
    <%= link_to 'sign out', sign_out_users_path, method: 'delete', id:'sign_out_link'%>
  </li>
  <% if user_signed_in? %>
  <li class="nav-item mx-4">
    <%= link_to 'edit', edit_users_path(current_user), id:'user_edit_link' %>
  </li>
  <li class="nav-item mr-4 ml-auto"><%= current_user.name %></li>
  <% end %>
</ul>

app/views/users/_error_message.html.erb
<% if @user.errors.any? %>
  <ul>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/users/edit.html.erb
<h1 class='text-center'>welcome to edit page</h1>
<%= render 'error_message' %>

<%=  form_for(@user, url: users_path, method: 'patch', :html => { class: 'col-6 m-auto text-danger'}) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.text_field :password, class:'form-control' %>
  </div>
  <%= f.submit 'update', class: "btn btn-primary", id:'update_btn' %>
<% end %>

app/views/users/sign_in.html.erb
<h1 class='text-center'>welcome to sign in page</h1>


<%=  form_for @user, html: { class: 'col-6 m-auto text-danger'}, url: login_users_path do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.text_field :password, class:'form-control' %>
  </div>
  <%= f.submit 'login', class: "btn btn-primary", id:'sign_in_btn' %>
<% end %>

app/views/users/sign_up.html.erb
<h1 class='text-center'>welcome to sign up page</h1>
<%= render 'error_message' %>

<%=  form_for @user, :html => { class: 'col-6 m-auto text-danger'} do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.text_field :password, class:'form-control' %>
  </div>
  <%= f.submit 'sign up', class: "btn btn-primary", id: 'sign_up_btn' %>
<% end %>